services:
  portfolio:
    build:
      context: .
      dockerfile: Containerfile
    container_name: dawwi-portfolio
    ports:
      - "3013:3013"
    environment:
      NODE_ENV: production
      PORT: 3013
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_SITE_URL: http://localhost:3013
      NEXT_PUBLIC_STRAPI_URL: https://strapi.cihuy-familly.my.id
    restart: unless-stopped
